# Konstanten definieren

ADD_NEURON = 0.15
ADD_WEIGHT = 0.6
CHANGE_WEIGHT = 0.8
BIAS = 0.5
REAC = False #dass ist ermal Unnötig


"""SPIELFELD START SETTINGS"""

SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 1000
FRAMES_PER_SECOND = 30

PRED_INIT_NUMB = 50
PREY_INIT_NUMB = 9 * PRED_INIT_NUMB

MAX_PRED_COUNT = 170
MAX_PREY_COUNT = 800


"""SIGHT RANGE"""

SIGHT_RANGE_PREDATOR = 200
SIGHT_RANGE_PREY = 100

NUMBER_SIGHTS_PREY = 24
NUMBER_SIGHTS_PREDATOR = 24

"""MUTATIONS PARAMETER"""
PREY_INIT_MUT = 12 #Mutatoin für Prey
PRED_INIT_MUT = 40 #Mutation für Predator


PRED_TIME_MOVE_DIST_WIDTH = 15
PREDATOR_SPEED = SCREEN_WIDTH/(FRAMES_PER_SECOND*PRED_TIME_MOVE_DIST_WIDTH)

#Energy
PRED_ENERGY = 100
PREDATOR_ENERGY_GAIN = 40 #kann ich noch abhängig von der totalen populationsgröße machen, je weniger pray, desto weniger energy_gain
PREDATOR_LIFESPAN = 15
PRED_DEFAULT_DECAY = PRED_ENERGY / (PREDATOR_LIFESPAN*FRAMES_PER_SECOND)
PRED_MOVING_DECAY = PRED_ENERGY/(2*SCREEN_WIDTH) #pred_energy/(2*pred_speed*10*30)

#PREY
#Movement
PREY_SPEED = 0.8 * PREDATOR_SPEED  # Preys starten mit Geschwindigkeit 0

#Energy
PREY_ENERGY = 50
PREY_REPRODUCATION_RATE = 16
PREY_MOVING_DECAY = PRED_ENERGY/(0.2*SCREEN_WIDTH)
PREY_REST_ENERGY_GAIN = PREY_ENERGY/(4*FRAMES_PER_SECOND)

